services:
  - type: web
    name: music-room-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server1.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
